export default function Disclaimer() {
  return (
    <main style={{maxWidth:"900px",margin:"40px auto",padding:"20px",lineHeight:"1.6"}}>
      <h1>Disclaimer</h1>

      <p>
        The information and tools provided on this website are for general 
        informational purposes only. While we strive to ensure accuracy and 
        reliability, we make no guarantees about the completeness, reliability, 
        or accuracy of any results generated by our tools.
      </p>

      <p>
        The use of any information or tools on this website is strictly at your 
        own risk. We are not responsible for any losses, damages, or issues that 
        may arise from the use of our services.
      </p>

      <p>
        Our website may contain links to external websites. We do not control 
        the nature, content, or availability of those sites and are not 
        responsible for their content.
      </p>

      <p>
        By using this website, you agree to this disclaimer and its terms.
      </p>
    </main>
  );
}